---

- name: Install MySQL
  action: apt pkg={{ item }}  state=present
  with_items:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev

- name: Create Zabbix user
  mysql_user:
    name: zabbix
    password: zabbix
    priv: 'zabbix.*:ALL'
    state: present


- name: Create Zabbix database
  mysql_db:
    name: zabbix
    encoding: utf8
    collation: utf8_bin
    state: present

- name: Importing Zabbix squema 
  shell: zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -uzabbix -p'zabbix' zabbix
    
