---

- hosts: ubuntu
  become: yes
  vars:
    file_version: 1.0

  tasks:
    - name: Create index.htlm
      template: 
        src: index.html.j2
        dest: /var/www/html/index.html
        mode: 0777


